# Generated by Django 3.2.23 on 2024-04-04 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20240328_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_rating_and_feedback',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app2.user_table'),
            preserve_default=False,
        ),
    ]
